export const translations = {
  en: {
    nav: {
      startBuilding: 'Start Analyzing',
      githubStars: '2.4k GitHub Stars'
    },
    hero: {
      tagline: 'Free GitHub Portfolio & Analytics Tool',
      title: 'Build Your Developer Brand',
      subtitle: 'With GitHub Analytics',
      description: 'Transform your GitHub activity into a professional portfolio. Showcase your contributions, visualize your coding patterns, and build your personal brand as a developer - 100% free forever.',
      ctaMain: 'Create Your Portfolio',
      ctaSecondary: 'See Example',
      noCreditCard: '100% Free Forever',
      quickSetup: '5-minute setup',
      githubOAuth: 'GitHub OAuth only'
    },
    trust: {
      commits: 'Repositories Analyzed',
      pullRequests: 'Beta Testers',
      developers: 'GitHub Stars',
      uptime: 'Days Since Launch'
    },
    features: {
      title: 'Powerful GitHub Analytics',
      subtitle: 'Deep insights into your repositories with AI-powered analysis',
      portfolio: {
        title: 'Repository Analytics',
        description: 'Comprehensive statistics including stars, forks, issues, contributors, and language breakdown. Track repository health and performance.',
        cta: 'See details'
      },
      coaching: {
        title: 'AI-Powered Analysis',
        description: 'Get health scores, competitor analysis, and actionable recommendations powered by Gemini AI to improve your projects.',
        cta: 'Learn more'
      },
      career: {
        title: 'Activity Visualizations',
        description: 'Beautiful commit heatmaps, time distributions, and contribution patterns to understand your development workflow.',
        cta: 'View charts'
      }
    },
    portfolio: {
      title: 'Transform Your GitHub Into a Stunning Portfolio',
      subtitle: 'Automatically generate a professional portfolio that showcases your best work',
      autoGenerated: {
        title: 'Auto-Generated from GitHub',
        description: 'Your portfolio updates automatically as you code. No manual updates needed.'
      },
      visualizations: {
        title: 'Rich Activity Visualizations',
        description: 'Beautiful charts and graphs that showcase your coding patterns and growth.'
      },
      skillTracking: {
        title: 'Skill & Growth Tracking',
        description: 'Highlight your expertise and show continuous improvement over time.'
      },
      ctaTitle: 'Ready to impress recruiters?',
      ctaSubtitle: 'Get your portfolio in 5 minutes',
      ctaButton: 'Get Started'
    },
    pricing: {
      title: 'Simple, Transparent Pricing',
      subtitle: '🎉 Launch Special: Everything FREE for a limited time!',
      monthly: 'Monthly',
      annual: 'Annual',
      save: 'Save 20%',
      perMonth: '/mo',
      bestValue: 'BEST VALUE',
      selectPlan: 'Start Free',
      startFreeTrial: 'Get Free Access',
      contactSales: 'Contact Sales',
      campaign: {
        badge: 'LIMITED TIME',
        originalPrice: 'Normally',
        freeNow: 'FREE NOW!'
      },
      plans: {
        free: {
          name: 'Free',
          features: ['10 Repository Analyses/month', 'Basic Statistics', 'Language Breakdown', 'Contributor List', '24-hour Data Cache']
        },
        professional: {
          name: 'Professional',
          originalPrice: '$9.8',
          features: ['Unlimited Repository Analyses', 'AI-Powered Insights', 'Commit Heatmaps', 'Time Distribution Charts', 'Personal Branding Tools', 'Portfolio Generation', 'Public Dashboard Sharing', 'Priority Support']
        },
        enterprise: {
          name: 'Enterprise',
          originalPrice: '$50',
          features: ['Everything in Pro', 'Team Collaboration (5 seats)', 'Custom API Access', 'Dedicated Support', 'Custom Integrations', 'SLA Guarantee']
        }
      }
    },
    testimonials: {
      title: 'Early Access Feedback',
      subtitle: 'What developers are saying about GitVue beta',
      reviews: [
        {
          name: 'T.S.',
          role: 'Individual Developer',
          text: 'The AI analysis is promising. Looking forward to seeing how this evolves with more features.'
        },
        {
          name: 'K.Y.',
          role: 'Tech Startup CEO',
          text: 'Clean interface and useful repository insights. Still testing but the potential is clear.'
        },
        {
          name: 'Anonymous',
          role: 'SaaS Founder',
          text: 'Interesting approach to GitHub analytics. The visualization features are particularly helpful.'
        }
      ]
    },
    cta: {
      title: 'Ready to Analyze Your Repositories?',
      subtitle: 'Be among the first to experience comprehensive GitHub analytics',
      button: 'Start Free Analysis',
      terms: 'No credit card required • 5-minute setup • Cancel anytime'
    }
  },
  ja: {
    nav: {
      startBuilding: '分析を開始',
      githubStars: '2.4k GitHub スター'
    },
    hero: {
      tagline: '無料のGitHubポートフォリオ＆分析ツール',
      title: '開発者ブランドを構築',
      subtitle: 'GitHub分析で',
      description: 'GitHubアクティビティをプロフェッショナルなポートフォリオに変換。貢献をショーケースし、コーディングパターンを可視化し、開発者としての個人ブランドを構築 - 完全無料でずっと。',
      ctaMain: 'ポートフォリオを作成',
      ctaSecondary: 'サンプルを見る',
      noCreditCard: '永久無料',
      quickSetup: '5分でセットアップ',
      githubOAuth: 'GitHub OAuth認証のみ'
    },
    trust: {
      commits: 'リポジトリ分析済み',
      pullRequests: 'ベータテスター',
      developers: 'GitHub スター',
      uptime: 'ローンチからの日数'
    },
    features: {
      title: '強力なGitHub分析',
      subtitle: 'AIを活用したリポジトリの深い洞察',
      portfolio: {
        title: 'リポジトリ分析',
        description: 'スター、フォーク、イシュー、コントリビューター、言語内訳を含む包括的な統計。リポジトリの健全性とパフォーマンスを追跡。',
        cta: '詳細を見る'
      },
      coaching: {
        title: 'AI分析機能',
        description: 'Gemini AIを活用した健全性スコア、競合分析、プロジェクト改善のための実用的な提案を取得。',
        cta: '詳細を見る'
      },
      career: {
        title: 'アクティビティ可視化',
        description: '美しいコミットヒートマップ、時間分布、貢献パターンで開発ワークフローを理解。',
        cta: 'チャートを表示'
      }
    },
    portfolio: {
      title: 'GitHubを素晴らしいポートフォリオに変換',
      subtitle: 'あなたの最高の作品を紹介するプロフェッショナルなポートフォリオを自動生成',
      autoGenerated: {
        title: 'GitHubから自動生成',
        description: 'コーディングすると自動的にポートフォリオが更新されます。手動更新は不要です。'
      },
      visualizations: {
        title: '豊富なアクティビティ可視化',
        description: 'コーディングパターンと成長を示す美しいチャートとグラフ。'
      },
      skillTracking: {
        title: 'スキル＆成長トラッキング',
        description: '専門知識を強調し、継続的な改善を示します。'
      },
      ctaTitle: '採用担当者を感動させる準備はできていますか？',
      ctaSubtitle: '5分でポートフォリオを取得',
      ctaButton: '開始する'
    },
    pricing: {
      title: 'シンプルで透明な価格設定',
      subtitle: '🎉 ローンチ特別キャンペーン：期間限定で全て無料！',
      monthly: '月額',
      annual: '年額',
      save: '20%お得',
      perMonth: '/月',
      bestValue: '最もお得',
      selectPlan: '無料で開始',
      startFreeTrial: '無料アクセスを取得',
      contactSales: '営業に問い合わせ',
      campaign: {
        badge: '期間限定',
        originalPrice: '通常価格',
        freeNow: '今だけ無料！'
      },
      plans: {
        free: {
          name: '無料',
          features: ['10リポジトリ分析/月', '基本統計', '言語内訳', 'コントリビューター一覧', '24時間データキャッシュ']
        },
        professional: {
          name: 'プロフェッショナル',
          originalPrice: '¥1,470',
          features: ['無制限のリポジトリ分析', 'AI分析機能', 'コミットヒートマップ', '時間分布チャート', '個人ブランディングツール', 'ポートフォリオ生成', '公開ダッシュボード共有', '優先サポート']
        },
        enterprise: {
          name: 'エンタープライズ',
          originalPrice: '¥7,500',
          features: ['Pro版の全機能', 'チームコラボレーション(5席)', 'カスタムAPIアクセス', '専任サポート', 'カスタム統合', 'SLA保証']
        }
      }
    },
    testimonials: {
      title: 'アーリーアクセスフィードバック',
      subtitle: 'GitVueベータ版への開発者の声',
      reviews: [
        {
          name: 'T.S.',
          role: '個人開発者',
          text: 'AI分析機能が期待できます。今後の機能追加でどう進化していくか楽しみです。'
        },
        {
          name: 'K.Y.',
          role: 'IT企業 CEO',
          text: 'クリーンなインターフェースと有用なリポジトリインサイト。まだテスト中ですが、可能性は明確です。'
        },
        {
          name: '匿名',
          role: 'SaaS創業者',
          text: 'GitHub分析への興味深いアプローチ。可視化機能が特に役立っています。'
        }
      ]
    },
    cta: {
      title: 'リポジトリを分析する準備はできましたか？',
      subtitle: '包括的なGitHub分析を最初に体験する開発者になりましょう',
      button: '無料分析を開始',
      terms: 'クレジットカード不要 • 5分でセットアップ • いつでもキャンセル可能'
    }
  }
};