export const translations = {
  en: {
    nav: {
      startBuilding: 'Start Building Your Portfolio',
      githubStars: '2.4k GitHub Stars'
    },
    hero: {
      tagline: 'Turn Your Coding Time Into Career Growth',
      title: 'Build Your Developer Portfolio',
      subtitle: 'While You Code',
      description: 'GitVue transforms your GitHub activity into career-advancing insights and a stunning portfolio - automatically. Get AI-powered coaching and showcase your coding journey to recruiters.',
      ctaMain: 'Start Building Your Portfolio',
      ctaSecondary: 'See Live Demo',
      noCreditCard: 'No credit card required',
      quickSetup: '5-minute setup',
      githubOAuth: 'GitHub OAuth only'
    },
    trust: {
      commits: 'Commits Analyzed',
      pullRequests: 'Pull Requests',
      developers: 'Active Developers',
      uptime: 'Uptime'
    },
    features: {
      title: 'Your Career Growth Platform',
      subtitle: 'More than analytics - it\'s your personal coding coach and portfolio builder',
      portfolio: {
        title: 'Auto Portfolio Generation',
        description: 'Transform your GitHub activity into a stunning developer portfolio. Perfect for job hunting and client acquisition.',
        cta: 'See examples'
      },
      coaching: {
        title: 'AI Coaching Insights',
        description: 'Get personalized productivity tips and skill development recommendations based on your coding patterns.',
        cta: 'Learn more'
      },
      career: {
        title: 'Career Growth Tracking',
        description: 'Monitor your skill development, set SMART goals, and track your progress toward career milestones.',
        cta: 'View metrics'
      }
    },
    portfolio: {
      title: 'Transform Your GitHub Into a Stunning Portfolio',
      subtitle: 'Automatically generate a professional portfolio that showcases your best work',
      autoGenerated: {
        title: 'Auto-Generated from GitHub',
        description: 'Your portfolio updates automatically as you code. No manual updates needed.'
      },
      visualizations: {
        title: 'Rich Activity Visualizations',
        description: 'Beautiful charts and graphs that showcase your coding patterns and growth.'
      },
      skillTracking: {
        title: 'Skill & Growth Tracking',
        description: 'Highlight your expertise and show continuous improvement over time.'
      },
      ctaTitle: 'Ready to impress recruiters?',
      ctaSubtitle: 'Get your portfolio in 5 minutes',
      ctaButton: 'Get Started'
    },
    pricing: {
      title: 'Simple, Transparent Pricing',
      subtitle: 'Choose the plan that fits your career goals',
      monthly: 'Monthly',
      annual: 'Annual',
      save: 'Save',
      perMonth: '/mo',
      bestValue: 'BEST VALUE',
      selectPlan: 'Select Plan',
      startFreeTrial: 'Start Free Trial',
      contactSales: 'Contact Sales',
      plans: {
        starter: {
          name: 'Starter',
          features: ['1 Project', 'Basic Analytics', '7-day History']
        },
        basic: {
          name: 'Basic',
          features: ['3 Projects', 'Basic Analytics', '30-day History', 'Email Reports']
        },
        professional: {
          name: 'Professional',
          features: ['10 Projects', 'AI Coaching', 'Portfolio Generator', 'Unlimited History', 'Priority Support', 'API Access']
        },
        enterprise: {
          name: 'Enterprise',
          features: ['Unlimited Projects', 'Custom Integrations', 'Team Management', 'SLA Support', 'SSO/SAML']
        }
      }
    },
    testimonials: {
      title: 'Loved by Developers Worldwide',
      subtitle: 'Join thousands of developers advancing their careers with GitVue',
      reviews: [
        {
          name: 'Sarah Chen',
          role: 'Senior Developer at Meta',
          text: 'GitVue\'s portfolio generator helped me land my dream job. The AI insights showed me exactly where to improve my coding habits.'
        },
        {
          name: 'Mike Johnson',
          role: 'Full Stack Developer',
          text: 'The AI coaching feature is like having a senior developer mentor. My productivity increased by 40% in just 2 months.'
        },
        {
          name: 'Lisa Park',
          role: 'Freelance Developer',
          text: 'Best $9.8 I spend each month. The portfolio alone has gotten me 3 new clients. ROI is incredible!'
        }
      ]
    },
    cta: {
      title: 'Ready to Accelerate Your Career?',
      subtitle: 'Join 15,000+ developers using GitVue to showcase their work and grow their careers',
      button: 'Start Your Free Trial Now',
      terms: 'No credit card required • 5-minute setup • Cancel anytime'
    }
  },
  ja: {
    nav: {
      startBuilding: 'ポートフォリオ作成を開始',
      githubStars: '2.4k GitHub スター'
    },
    hero: {
      tagline: 'コーディング時間をキャリア成長に変える',
      title: '開発者ポートフォリオを',
      subtitle: 'コーディングしながら構築',
      description: 'GitVueはGitHubアクティビティを自動的にキャリアを前進させる洞察と素晴らしいポートフォリオに変換します。AIによるコーチングを受け、あなたのコーディングジャーニーを採用担当者にアピールしましょう。',
      ctaMain: 'ポートフォリオ作成を開始',
      ctaSecondary: 'ライブデモを見る',
      noCreditCard: 'クレジットカード不要',
      quickSetup: '5分でセットアップ',
      githubOAuth: 'GitHub OAuth認証のみ'
    },
    trust: {
      commits: 'コミット分析済み',
      pullRequests: 'プルリクエスト',
      developers: 'アクティブ開発者',
      uptime: '稼働率'
    },
    features: {
      title: 'あなたのキャリア成長プラットフォーム',
      subtitle: '単なる分析ツールではなく、パーソナルコーディングコーチとポートフォリオビルダー',
      portfolio: {
        title: '自動ポートフォリオ生成',
        description: 'GitHubアクティビティを素晴らしい開発者ポートフォリオに変換。転職活動やクライアント獲得に最適。',
        cta: '例を見る'
      },
      coaching: {
        title: 'AIコーチング洞察',
        description: 'コーディングパターンに基づいた、パーソナライズされた生産性のヒントとスキル開発の推奨事項を取得。',
        cta: '詳細を見る'
      },
      career: {
        title: 'キャリア成長トラッキング',
        description: 'スキル開発を監視し、SMARTゴールを設定し、キャリアマイルストーンへの進捗を追跡。',
        cta: 'メトリクスを表示'
      }
    },
    portfolio: {
      title: 'GitHubを素晴らしいポートフォリオに変換',
      subtitle: 'あなたの最高の作品を紹介するプロフェッショナルなポートフォリオを自動生成',
      autoGenerated: {
        title: 'GitHubから自動生成',
        description: 'コーディングすると自動的にポートフォリオが更新されます。手動更新は不要です。'
      },
      visualizations: {
        title: '豊富なアクティビティ可視化',
        description: 'コーディングパターンと成長を示す美しいチャートとグラフ。'
      },
      skillTracking: {
        title: 'スキル＆成長トラッキング',
        description: '専門知識を強調し、継続的な改善を示します。'
      },
      ctaTitle: '採用担当者を感動させる準備はできていますか？',
      ctaSubtitle: '5分でポートフォリオを取得',
      ctaButton: '開始する'
    },
    pricing: {
      title: 'シンプルで透明な価格設定',
      subtitle: 'キャリア目標に合ったプランを選択',
      monthly: '月額',
      annual: '年額',
      save: 'お得',
      perMonth: '/月',
      bestValue: '最もお得',
      selectPlan: 'プランを選択',
      startFreeTrial: '無料トライアル開始',
      contactSales: '営業に問い合わせ',
      plans: {
        starter: {
          name: 'スターター',
          features: ['1プロジェクト', '基本分析', '7日間の履歴']
        },
        basic: {
          name: 'ベーシック',
          features: ['3プロジェクト', '基本分析', '30日間の履歴', 'メールレポート']
        },
        professional: {
          name: 'プロフェッショナル',
          features: ['10プロジェクト', 'AIコーチング', 'ポートフォリオ生成', '無制限履歴', '優先サポート', 'APIアクセス']
        },
        enterprise: {
          name: 'エンタープライズ',
          features: ['無制限プロジェクト', 'カスタム統合', 'チーム管理', 'SLAサポート', 'SSO/SAML']
        }
      }
    },
    testimonials: {
      title: '世界中の開発者に愛されています',
      subtitle: 'GitVueでキャリアを前進させている数千人の開発者に加わりましょう',
      reviews: [
        {
          name: 'サラ・チェン',
          role: 'Meta シニア開発者',
          text: 'GitVueのポートフォリオジェネレーターは私の夢の仕事を得るのに役立ちました。AI洞察は私のコーディング習慣を改善すべき場所を正確に示してくれました。'
        },
        {
          name: 'マイク・ジョンソン',
          role: 'フルスタック開発者',
          text: 'AIコーチング機能は、シニア開発者のメンターがいるようなものです。わずか2か月で生産性が40％向上しました。'
        },
        {
          name: 'リサ・パーク',
          role: 'フリーランス開発者',
          text: '毎月使う最高の$9.8です。ポートフォリオだけで3つの新しいクライアントを獲得しました。ROIは信じられないほどです！'
        }
      ]
    },
    cta: {
      title: 'キャリアを加速する準備はできていますか？',
      subtitle: 'GitVueを使用して作品を紹介し、キャリアを成長させている15,000人以上の開発者に参加',
      button: '今すぐ無料トライアルを開始',
      terms: 'クレジットカード不要 • 5分でセットアップ • いつでもキャンセル可能'
    }
  }
};