export const translations = {
  en: {
    nav: {
      startBuilding: 'Start Analyzing',
      githubStars: '2.4k GitHub Stars'
    },
    hero: {
      tagline: 'AI-Powered GitHub Repository Analytics',
      title: 'Analyze Your GitHub Projects',
      subtitle: 'With AI Insights',
      description: 'GitVue provides comprehensive GitHub repository analytics with AI-powered insights. Track commits, contributors, languages, and get actionable recommendations to improve your projects.',
      ctaMain: 'Start Analyzing',
      ctaSecondary: 'See Live Demo',
      noCreditCard: 'No credit card required',
      quickSetup: '5-minute setup',
      githubOAuth: 'GitHub OAuth only'
    },
    trust: {
      commits: 'Repositories Analyzed',
      pullRequests: 'Beta Testers',
      developers: 'GitHub Stars',
      uptime: 'Days Since Launch'
    },
    features: {
      title: 'Powerful GitHub Analytics',
      subtitle: 'Deep insights into your repositories with AI-powered analysis',
      portfolio: {
        title: 'Repository Analytics',
        description: 'Comprehensive statistics including stars, forks, issues, contributors, and language breakdown. Track repository health and performance.',
        cta: 'See details'
      },
      coaching: {
        title: 'AI-Powered Analysis',
        description: 'Get health scores, competitor analysis, and actionable recommendations powered by Gemini AI to improve your projects.',
        cta: 'Learn more'
      },
      career: {
        title: 'Activity Visualizations',
        description: 'Beautiful commit heatmaps, time distributions, and contribution patterns to understand your development workflow.',
        cta: 'View charts'
      }
    },
    portfolio: {
      title: 'Transform Your GitHub Into a Stunning Portfolio',
      subtitle: 'Automatically generate a professional portfolio that showcases your best work',
      autoGenerated: {
        title: 'Auto-Generated from GitHub',
        description: 'Your portfolio updates automatically as you code. No manual updates needed.'
      },
      visualizations: {
        title: 'Rich Activity Visualizations',
        description: 'Beautiful charts and graphs that showcase your coding patterns and growth.'
      },
      skillTracking: {
        title: 'Skill & Growth Tracking',
        description: 'Highlight your expertise and show continuous improvement over time.'
      },
      ctaTitle: 'Ready to impress recruiters?',
      ctaSubtitle: 'Get your portfolio in 5 minutes',
      ctaButton: 'Get Started'
    },
    pricing: {
      title: 'Simple, Transparent Pricing',
      subtitle: 'Choose the plan that fits your career goals',
      monthly: 'Monthly',
      annual: 'Annual',
      save: 'Save',
      perMonth: '/mo',
      bestValue: 'BEST VALUE',
      selectPlan: 'Select Plan',
      startFreeTrial: 'Start Free Trial',
      contactSales: 'Contact Sales',
      plans: {
        free: {
          name: 'Free',
          features: ['10 Repository Analyses/month', 'Basic Statistics', 'Language Breakdown', 'Contributor List', '7-day Data Cache']
        },
        professional: {
          name: 'Professional',
          features: ['100 Repository Analyses/month', '100 AI Analyses/month', 'Commit Heatmaps', 'Time Distribution Charts', 'Competitor Analysis', 'Health Scoring', 'Public Dashboard Sharing', 'Priority Support']
        },
        enterprise: {
          name: 'Enterprise',
          features: ['Unlimited Analyses', 'All Pro Features', 'Custom API Access', 'Dedicated Support', 'Custom Integrations', 'SLA Guarantee']
        }
      }
    },
    testimonials: {
      title: 'Early Access Feedback',
      subtitle: 'What developers are saying about GitVue beta',
      reviews: [
        {
          name: 'T.S.',
          role: 'Individual Developer',
          text: 'The AI analysis is promising. Looking forward to seeing how this evolves with more features.'
        },
        {
          name: 'K.Y.',
          role: 'Tech Startup CEO',
          text: 'Clean interface and useful repository insights. Still testing but the potential is clear.'
        },
        {
          name: 'Anonymous',
          role: 'SaaS Founder',
          text: 'Interesting approach to GitHub analytics. The visualization features are particularly helpful.'
        }
      ]
    },
    cta: {
      title: 'Ready to Analyze Your Repositories?',
      subtitle: 'Be among the first to experience comprehensive GitHub analytics',
      button: 'Start Free Analysis',
      terms: 'No credit card required • 5-minute setup • Cancel anytime'
    }
  },
  ja: {
    nav: {
      startBuilding: '分析を開始',
      githubStars: '2.4k GitHub スター'
    },
    hero: {
      tagline: 'AI搭載GitHubリポジトリ分析',
      title: 'GitHubプロジェクトを',
      subtitle: 'AIで分析',
      description: 'GitVueはAIを活用した包括的なGitHubリポジトリ分析を提供します。コミット、コントリビューター、言語を追跡し、プロジェクト改善のための実用的な提案を取得します。',
      ctaMain: '分析を開始',
      ctaSecondary: 'ライブデモを見る',
      noCreditCard: 'クレジットカード不要',
      quickSetup: '5分でセットアップ',
      githubOAuth: 'GitHub OAuth認証のみ'
    },
    trust: {
      commits: 'リポジトリ分析済み',
      pullRequests: 'ベータテスター',
      developers: 'GitHub スター',
      uptime: 'ローンチからの日数'
    },
    features: {
      title: '強力なGitHub分析',
      subtitle: 'AIを活用したリポジトリの深い洞察',
      portfolio: {
        title: 'リポジトリ分析',
        description: 'スター、フォーク、イシュー、コントリビューター、言語内訳を含む包括的な統計。リポジトリの健全性とパフォーマンスを追跡。',
        cta: '詳細を見る'
      },
      coaching: {
        title: 'AI分析機能',
        description: 'Gemini AIを活用した健全性スコア、競合分析、プロジェクト改善のための実用的な提案を取得。',
        cta: '詳細を見る'
      },
      career: {
        title: 'アクティビティ可視化',
        description: '美しいコミットヒートマップ、時間分布、貢献パターンで開発ワークフローを理解。',
        cta: 'チャートを表示'
      }
    },
    portfolio: {
      title: 'GitHubを素晴らしいポートフォリオに変換',
      subtitle: 'あなたの最高の作品を紹介するプロフェッショナルなポートフォリオを自動生成',
      autoGenerated: {
        title: 'GitHubから自動生成',
        description: 'コーディングすると自動的にポートフォリオが更新されます。手動更新は不要です。'
      },
      visualizations: {
        title: '豊富なアクティビティ可視化',
        description: 'コーディングパターンと成長を示す美しいチャートとグラフ。'
      },
      skillTracking: {
        title: 'スキル＆成長トラッキング',
        description: '専門知識を強調し、継続的な改善を示します。'
      },
      ctaTitle: '採用担当者を感動させる準備はできていますか？',
      ctaSubtitle: '5分でポートフォリオを取得',
      ctaButton: '開始する'
    },
    pricing: {
      title: 'シンプルで透明な価格設定',
      subtitle: 'キャリア目標に合ったプランを選択',
      monthly: '月額',
      annual: '年額',
      save: 'お得',
      perMonth: '/月',
      bestValue: '最もお得',
      selectPlan: 'プランを選択',
      startFreeTrial: '無料トライアル開始',
      contactSales: '営業に問い合わせ',
      plans: {
        free: {
          name: '無料',
          features: ['10リポジトリ分析/月', '基本統計', '言語内訳', 'コントリビューター一覧', '7日間のデータキャッシュ']
        },
        professional: {
          name: 'プロフェッショナル',
          features: ['100リポジトリ分析/月', '100 AI分析/月', 'コミットヒートマップ', '時間分布チャート', '競合分析', '健全性スコアリング', '公開ダッシュボード共有', '優先サポート']
        },
        enterprise: {
          name: 'エンタープライズ',
          features: ['無制限分析', '全Pro機能', 'カスタムAPIアクセス', '専任サポート', 'カスタム統合', 'SLA保証']
        }
      }
    },
    testimonials: {
      title: 'アーリーアクセスフィードバック',
      subtitle: 'GitVueベータ版への開発者の声',
      reviews: [
        {
          name: 'T.S.',
          role: '個人開発者',
          text: 'AI分析機能が期待できます。今後の機能追加でどう進化していくか楽しみです。'
        },
        {
          name: 'K.Y.',
          role: 'IT企業 CEO',
          text: 'クリーンなインターフェースと有用なリポジトリインサイト。まだテスト中ですが、可能性は明確です。'
        },
        {
          name: '匿名',
          role: 'SaaS創業者',
          text: 'GitHub分析への興味深いアプローチ。可視化機能が特に役立っています。'
        }
      ]
    },
    cta: {
      title: 'リポジトリを分析する準備はできましたか？',
      subtitle: '包括的なGitHub分析を最初に体験する開発者になりましょう',
      button: '無料分析を開始',
      terms: 'クレジットカード不要 • 5分でセットアップ • いつでもキャンセル可能'
    }
  }
};