export const portfolioTranslations = {
  en: {
    title: 'Transform Your GitHub Into a Stunning Portfolio',
    subtitle: 'Automatically generate a professional portfolio that showcases your best work',
    profileName: 'John Developer',
    profileRole: 'Full Stack Engineer',
    location: 'San Francisco',
    statsCommits: 'Commits',
    statsPRs: 'PRs Merged',
    statsStars: 'Stars Earned',
    featuredProjects: 'Featured Projects',
    projectDesc1: 'A modern React application with TypeScript',
    projectDesc2: 'Scalable machine learning pipeline',
    features: {
      autoGenerated: {
        title: 'Auto-Generated from GitHub',
        description: 'Your portfolio updates automatically as you code. No manual updates needed.'
      },
      visualizations: {
        title: 'Rich Activity Visualizations',
        description: 'Beautiful charts and graphs that showcase your coding patterns and growth.'
      },
      skillTracking: {
        title: 'Skill & Growth Tracking',
        description: 'Highlight your expertise and show continuous improvement over time.'
      }
    },
    ctaTitle: 'Ready to impress recruiters?',
    ctaSubtitle: 'Get your portfolio in 5 minutes',
    ctaButton: 'Get Started'
  },
  ja: {
    title: 'GitHubを素晴らしいポートフォリオに変換',
    subtitle: 'あなたの最高の作品を紹介するプロフェッショナルなポートフォリオを自動生成',
    profileName: 'ジョン 開発者',
    profileRole: 'フルスタックエンジニア',
    location: 'サンフランシスコ',
    statsCommits: 'コミット',
    statsPRs: 'マージ済みPR',
    statsStars: '獲得スター',
    featuredProjects: '注目のプロジェクト',
    projectDesc1: 'TypeScriptを使用したモダンなReactアプリケーション',
    projectDesc2: 'スケーラブルな機械学習パイプライン',
    features: {
      autoGenerated: {
        title: 'GitHubから自動生成',
        description: 'コーディングすると自動的にポートフォリオが更新されます。手動更新は不要です。'
      },
      visualizations: {
        title: '豊富なアクティビティ可視化',
        description: 'コーディングパターンと成長を示す美しいチャートとグラフ。'
      },
      skillTracking: {
        title: 'スキル＆成長トラッキング',
        description: '専門知識を強調し、継続的な改善を示します。'
      }
    },
    ctaTitle: '採用担当者を感動させる準備はできていますか？',
    ctaSubtitle: '5分でポートフォリオを取得',
    ctaButton: '開始する'
  }
};